vich_uploader:
    db_driver: orm

    mappings:
        profile_pics:
            uri_prefix: /assets/uploads/profile_pics
            upload_destination: '%kernel.project_dir%/public/assets/uploads/profile_pics'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
